# Generated by Django 2.2 on 2022-04-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_rename_uploda_by_userfiles_upload_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfiles',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
