# Generated by Django 4.0.3 on 2022-09-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_auto_20220425_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfiles',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
